name: build

on:
  push:  # 해당 브랜치에 push가 들어올 경우 workflow 실행
    branches:
      - dev
      - stg

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # build 권한 추가
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # build
      - name: Build with Gradle Wrapper
        run: ./gradlew build

      # file 이름 설정, 압축
      - name: Zip files
        run: |
          tar -zcvf ./communicator-$(date "+%Y-%m-%d").tar.gz -C ./build/libs/ communicator-0.0.1-SNAPSHOT.war
          ls -al
          pwd
          
      # Google Cloud Service Account credential auth
      - name: Google auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # 압축파일 google cloud storage로 전송
      # bucket_name/branch 디렉토리 하위로 전송됨
      - name: Copy tar file to Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: communicator-$(date "+%Y-%m-%d").tar.gz
          destination: ew1-dvs-prod-storage/${{ github.ref_name }}/appl/communicator/
          
    # Jenkins 시작 이벤트 발생 조건
      # - name: trigger Jenkins job
      #   uses: appleboy/jenkins-action@master
      #   with:
      #     url: "${{ secrets.HOST }}"  # Jenkins URL
      #     user: "${{ secrets.USER }}"  # Jenkins에서 job을 실행할 user
      #     token: "${{ secrets.JENKINSAPI }}"  # Jenkins에서 user의 API Token
      #     job: "communicator"  # 시작할 job
