name: build

on:
  push:  # 해당 브랜치에 push가 들어올 경우 workflow 실행
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # # build 권한 추가
      # - name: Grant execute permission for gradlew
      #   run: chmod +x ./gradlew

      # # build
      # - name: Build with Gradle Wrapper
      #   run: ./gradlew build

      # # file 이름 설정, 압축
      # - name: Zip files
      #   run:
      #     tar -zcvf ./communicator-$(date "+%Y-%m-%d").tar.gz -C ./build/libs/ communicator-0.0.1-SNAPSHOT.war

      # Google Cloud Service Account credential auth
      - name: Google auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # gcloud 명령어 사용을 위한 Google Cloud SDK 구성
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # 압축파일 google cloud storage로 전송
      # bucket_name/branch 디렉토리 하위로 전송됨
      # - name: Copy tar file to Cloud Storage
      #   run: gcloud storage cp ./communicator-$(date "+%Y-%m-%d").tar.gz gs://ew1-dvs-dev-storage/${{ github.ref_name }}/appl/communicator/

      - name: ssh to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER }}
          username: ubuntu
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            cat hi.txt
